variables:
  serviceConnection: RG-SIS-App-DRDP-001
  logicalName: sqldbsrv002q

pool:
  vmImage: windows-latest
 
steps: 
- task: DRDPAppConfiguration@0
  displayName: ophalen connectionstring
  inputs:
    command: get
    azureServiceConnection: $(serviceConnection)
    appConfiguration: infra-app-config
    key: $(sqldbsrv002q).connection-string-ado.net
    outputVariable: connectionstring
    resolveSecret: true