trigger:
- main

pool: 
  vmImage: 'windows-latest'

variables:
  serviceConnection: RG-SIS-App-DRDP-002
  logicalName: drdp-sql-database
  logicalNameServer: qaiss-sql-server
  sqlFile: $(build.SourcesDirectory)\qtable.sql
 
steps:
- task: AzureMysqlDeployment@1
  displayName: Deploy table
  inputs:
    azureSubscription: 'RG-SIS-App-DRDP-002'
    ServerName: 'demosqlsrvq.database.windows.net'
    DatabaseName: 'demosqldbq'
    SqlUsername: 'sqlqaiss'
    SqlPassword: 'Drdpwachtw00rd'
    TaskNameSelector: 'SqlTaskFile'
    SqlFile: '$(Build.SourcesDirectory)/qtabel.sql'
    IpDetectionMethod: 'AutoDetect'
    DeleteFirewallRule: false